on:
  push:
    branches:
      - main

jobs:
  build-site:
    if: github.repository == 'jades-projects/lesble'
    name: Build the site
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: build
        run: ./build.sh
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pub
          cname: lesble.jade.fyi



